site_name: wql2002's blog
site_description: wql2002's personal blog, including learning materials, course notes, etc.
site_url: http://www.example.com

# repo info
repo_name: wql2002/blog
repo_url: https://github.com/wql2002/blog

# copyright info
copyright: Copyright &copy; 2024 ~ now | Qianliang Wu

theme:
  name: material
  features:
  - content.code.copy
  - navigation.indexes
  - navigation.tabs
  - navigation.top
  - navigation.sections
  - search.highlight
  - toc.follow

plugins:
  - search
  - include_dir_to_nav
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      # categories_allowed:
      #   - TBA
      pagination_per_page: 10
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tags
  - rss:
      match_path: "blog/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  social:
    - icon: fontawesome/solid/house
      link: https://wql2002.github.io/
    - icon: fontawesome/brands/github
      link: https://github.com/wql2002
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/qianliang-wu-370551253/

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Linux: 
    - Linux/index.md
    - Posts: Linux/posts